#!/usr/bin/env python3
"""
ZoPhysicist build.

Scans content/*.tex, reads the `% !ZP key = value` headers, converts the
LaTeX body to an HTML fragment with Pandoc, and auto-generates
content/manifest.json. The result is assembled in ./site, ready to deploy.

Authors never edit JSON. Adding a file + header = done.
"""
import json, os, re, subprocess, sys, shutil

ROOT       = os.path.dirname(os.path.abspath(__file__))
CONTENT    = os.path.join(ROOT, "content")
SHELL      = os.path.join(ROOT, "shell")
OUT        = os.path.join(ROOT, "site")
OUT_CONT   = os.path.join(OUT, "content")
VALID_TYPES = {"lecture", "definition", "problem", "solution"}
HEADER_RE  = re.compile(r"^\s*%\s*!ZP\s+([A-Za-z_]+)\s*=\s*(.*?)\s*$")
MIZO_RE    = re.compile(r"^\s*%%%\s*MIZO\s*%%%\s*$")

errors = []
def err(f, msg): errors.append(f"  [{f}] {msg}")

def slug(s):
    s = re.sub(r"[^A-Za-z0-9]+", "-", s.strip().lower())
    return re.sub(r"(^-+|-+$)", "", s) or "untitled"

def pandoc(latex):
    p = subprocess.run(
        ["pandoc", "-f", "latex", "-t", "html5", "--mathjax", "--wrap=preserve"],
        input=latex, capture_output=True, text=True)
    if p.returncode != 0:
        return None, p.stderr.strip()
    return p.stdout, None

def parse(path):
    raw = open(path, encoding="utf-8").read().splitlines()
    meta, body_lines = {}, []
    for line in raw:
        m = HEADER_RE.match(line)
        if m:
            meta[m.group(1).lower()] = m.group(2)
        else:
            body_lines.append(line)
    en, lus, sink = [], [], None
    for line in body_lines:
        if MIZO_RE.match(line):
            sink = lus; continue
        (lus if sink is lus else en).append(line)
    return meta, "\n".join(en).strip(), "\n".join(lus).strip()

def main():
    if shutil.which("pandoc") is None:
        print("ERROR: pandoc is not installed."); sys.exit(1)

    files = sorted(f for f in os.listdir(CONTENT)
                   if f.endswith(".tex") and not f.startswith("_"))
    if not files:
        print("ERROR: no .tex content files found in content/."); sys.exit(1)

    os.makedirs(OUT_CONT, exist_ok=True)
    # clean previous fragments
    for f in os.listdir(OUT_CONT):
        if f.endswith(".html") or f == "manifest.json":
            os.remove(os.path.join(OUT_CONT, f))

    topics, entries, pairs = {}, [], {}

    for idx, fn in enumerate(files):
        path = os.path.join(CONTENT, fn)
        meta, en, lus = parse(path)

        for req in ("title", "type", "topic"):
            if not meta.get(req):
                err(fn, f"missing required header  % !ZP {req} = ...")
        typ = meta.get("type", "").lower()
        if typ and typ not in VALID_TYPES:
            err(fn, f"type '{typ}' must be one of: {', '.join(sorted(VALID_TYPES))}")
        if errors:
            continue

        eid    = slug(meta.get("id") or os.path.splitext(fn)[0])
        tslug  = slug(meta["topic"])
        t = topics.setdefault(tslug, {"id": tslug, "title_en": meta["topic"],
                                      "order": 100 + idx})
        if meta.get("topicorder"):
            try: t["order"] = int(meta["topicorder"])
            except ValueError: err(fn, "topicorder must be a number")

        html, e_err = pandoc(en or "\\emph{(no content yet)}")
        if e_err: err(fn, f"Pandoc could not convert this LaTeX:\n      {e_err}")
        if errors: continue
        open(os.path.join(OUT_CONT, eid + ".html"), "w", encoding="utf-8").write(html)

        entry = {
            "id": eid, "type": typ, "topic": tslug,
            "file": eid + ".html",
            "title_en": meta["title"],
            "summary_en": meta.get("summary", ""),
            "tags": [x.strip() for x in meta.get("tags", "").split(",") if x.strip()],
        }
        try: entry["order"] = int(meta.get("order", 100 + idx))
        except ValueError: entry["order"] = 100 + idx

        if lus:
            lhtml, l_err = pandoc(lus)
            if l_err: err(fn, f"Pandoc failed on the Mizo section:\n      {l_err}")
            else:
                open(os.path.join(OUT_CONT, eid + ".lus.html"),
                     "w", encoding="utf-8").write(lhtml)
                entry["file_lus"] = eid + ".lus.html"

        if meta.get("pair"):
            pairs.setdefault(meta["pair"], {})[typ] = eid
        entries.append(entry)

    if errors:
        print("\nBUILD FAILED — fix these and commit again:\n")
        print("\n".join(errors)); sys.exit(1)

    # auto-link problems <-> solutions sharing a `pair` value
    by_id = {e["id"]: e for e in entries}
    for p in pairs.values():
        if "problem" in p and "solution" in p:
            by_id[p["problem"]]["solution"] = p["solution"]
            by_id[p["solution"]]["problem"] = p["problem"]

    manifest = {
        "_generated": "Auto-generated by build.py — do not edit by hand.",
        "topics": sorted(topics.values(), key=lambda t: (t["order"], t["title_en"])),
        "entries": sorted(entries, key=lambda e: (e["topic"], e["order"], e["title_en"])),
    }
    json.dump(manifest, open(os.path.join(OUT_CONT, "manifest.json"), "w",
              encoding="utf-8"), ensure_ascii=False, indent=2)

    # copy the static shell (index.html, i18n.json, .htaccess)
    for f in os.listdir(SHELL):
        shutil.copy(os.path.join(SHELL, f), os.path.join(OUT, f))

    print(f"OK — {len(entries)} entries across {len(topics)} topics -> ./site")

if __name__ == "__main__":
    main()
